server:
  port: 80
  context-path: /
management:
  port: 8080
  security:
      enabled: false
spring:
  main:
      banner-mode: console
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
          url: jdbc:mysql://localhost:3306/moon?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
          username: root
          password: 1234qwer
          driver-class-name: com.mysql.cj.jdbc.Driver
          filters: config,stat,slf4j,wall
          test-on-borrow: true
          test-on-return: true
          filter:
             stat:
                db-type: mysql
                merge-sql: true
                slow-sql-millis: 1000
                log-slow-sql: true
             wall:
                enabled: true
                db-type: mysql
                config:
                  drop-table-allow: false